export const mockOrderDetails = {
  "ORD-001": {
    id: "ORD-001",
    customer: "Alice Johnson",
    email: "alice.johnson@email.com",
    phone: "+1 (555) 123-4567",
    status: "Processing",
    statusColor: "bg-accent text-accent-foreground",
    date: "2024-01-15",
    total: "$299.99",
    subtotal: "$279.99",
    shipping: "$15.00",
    tax: "$5.00",
    canCancel: true,
    shippingAddress: {
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zip: "10001",
      country: "United States",
    },
    paymentMethod: {
      type: "Credit Card",
      last4: "4242",
      brand: "Visa",
    },
    items: [
      {
        id: 1,
        name: "Wireless Bluetooth Headphones",
        image: "/wireless-headphones.png",
        price: "$149.99",
        quantity: 1,
        sku: "WBH-001",
      },
      {
        id: 2,
        name: "Smartphone Case",
        image: "/colorful-phone-case-display.png",
        price: "$29.99",
        quantity: 2,
        sku: "SC-002",
      },
      {
        id: 3,
        name: "USB-C Cable",
        image: "/usb-cable.png",
        price: "$19.99",
        quantity: 5,
        sku: "USB-003",
      },
    ],
    timeline: [
      { status: "Order Placed", date: "2024-01-15 10:30 AM", completed: true },
      { status: "Payment Confirmed", date: "2024-01-15 10:32 AM", completed: true },
      { status: "Processing", date: "2024-01-15 11:00 AM", completed: true },
      { status: "Shipped", date: "Pending", completed: false },
      { status: "Delivered", date: "Pending", completed: false },
    ],
  },
}