import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/context/Provider";
import Navbar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";
import Banner from "@/components/LadingPage/Banner";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          
              <Navbar />
              <main className="">{children}</main>
               <Banner/>
              <Footer />
              <Toaster position="top-center" richColors closeButton />
              
        </QueryProvider>
      </body>
    </html>
  );
}
