import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/context/Provider";
import { CartProvider } from "@/context/CartContext";
import AppContextProvider from "@/context/AppContextProvider";
import Navbar from "@/components/layout/NavBar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <AppContextProvider>
            <CartProvider>
              <Navbar />
              <main className="">{children}</main>
              <Footer />
              <Toaster position="top-right" reverseOrder={false} />
            </CartProvider>
          </AppContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
